
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${TF_VAR_POSTGRES_DATABASE}
      POSTGRES_USER: ${TF_VAR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TF_VAR_POSTGRES_PASSWORD}
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres_dw:
    image: postgres:15
    container_name: postgres_dw
    environment:
      POSTGRES_DB: ${TF_VAR_POSTGRES_DW_DATABASE}
      POSTGRES_USER: ${TF_VAR_POSTGRES_DW_USER}
      POSTGRES_PASSWORD: ${TF_VAR_POSTGRES_DW_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - pgdata_dw:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${TF_VAR_MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${TF_VAR_MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    command: >
      bash -c "
        /opt/airflow/scripts/entrypoint.sh
      "
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    env_file:
      - .env 
    volumes:
      - ${HOST_PROJECT_ROOT}/airflow_config/dags:/opt/airflow/dags
      - ${HOST_PROJECT_ROOT}/airflow_config/logs:/opt/airflow/logs
      - ${HOST_PROJECT_ROOT}/airflow_config/scripts:/opt/airflow/scripts
      - ${HOST_PROJECT_ROOT}/dist:/opt/airflow/lib
    ports:
      - "8081:8080"

volumes:
  pgdata:
  pgdata_dw:
  minio_data:

networks:
  default:
    # Remplace par le nom EXACT trouvé à l'étape 1
    name: projet-mig8110_devcontainer_default
    external: true