[project]
name = "proct_olis"
version = "1.0"
description = "Default template for PDM package"
authors = [
    {name = "imen-bendai", email = "imen.bendai@outlook.com"},
]
dependencies = [
    "click",
    "pyyaml",
    "polars",
    "pandas<2.2",
    "minio",
    "requests",
    "s3fs",
    "dotenv",
    "connectorx>=0.3.2",
    "pyarrow",
    "sqlalchemy",
    "psycopg2-binary",
    "numpy>=2.2.6",
    "apache-airflow",
    "fsspec==2023.12.2"
]
requires-python = "<3.13,>=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
[dependency-groups]
lint = [
    "ruff",
    "flake8",
    "black"
]
 
dev = [
    "pytest",
    "ipykernel",
    "pyspark",
    "notebook>=7.4.7",
    "jupyter>=1.1.1",
]

[project.scripts]
transformation = "proct_olis.app:main"

[tool.pdm.scripts]
_.env_file = ".env"
infra-up = {shell = "docker compose up -d"}
infra-down = {shell = "docker compose down -v"}
init = {shell = "terraform -chdir=infrastructure init"}
plan = {shell = "terraform -chdir=infrastructure plan -out=tfplan"}
apply = {shell = "terraform -chdir=infrastructure apply tfplan"}
destroy = {shell = "terraform -chdir=infrastructure destroy -auto-approve"}
clean-dist = { shell = "rm -rf dist" }
build-lib = "pdm build"
restart-container = "docker restart airflow"
install-whl = "docker exec airflow bash -c 'pip install --force-reinstall /opt/airflow/lib/proct_olis-1.0-py3-none-any.whl'"
deploy-lib = { composite = ["clean-dist", "build-lib", "restart-container", "install-whl"]}

seed = { call = "scripts.init_datalke:main"}

install_infra = { composite = ["apply", "seed"]}

[tool.pdm.build]
includes = []
excludes = ["scripts/"]