sources:
  datalake.orders:
    type: s3
    bucket_name: raw-data
    file_name: orders
    file_extension: parquet
    columns:
      order_id: order_id
      customer_id: customer_id
      order_status: order_status
      order_purchase_timestamp: order_purchase_timestamp
      order_estimated_delivery_date: order_estimated_delivery_date
      order_approved_at: order_approved_at
      order_delivered_carrier_date: order_delivered_carrier_date
      order_delivered_customer_date: order_delivered_customer_date

destination:
  table: orders
  schema: public
  primary_key: order_id
  business_keys:
    - order_id
  kind: append
  destination_type: postgres_operational
