sources:
  datalake.order_items:
    type: s3
    bucket_name: raw-data 
    file_name: order_items
    file_extension: parquet 
    columns:
      product_id: product_id
      seller_id: seller_id
      price: price
    filter_statement: "product_id is not null"

destination:
  table: product_seller
  schema: public
  primary_key: product_id
  business_keys:
    - product_id
    - seller_id
  kind: append
  destination_type: postgres_operational