sources:
  datalake.products:
    type: s3
    bucket_name: raw-data
    file_name: products
    file_extension: parquet
    columns:
      product_category_name: product_category_name
    filter_statement: "product_category_name is not null"
  datalake.ref_product_category_name_translation:
    type: s3
    bucket_name: raw-data
    file_name: ref-product-category-name-translation
    file_extension: parquet
    columns:
      product_category_name: category_name_es
      product_category_name_english: category_name_en
destination:
  table: product_category
  schema: public
  primary_key: product_category_id
  business_keys:
    - product_category_name
  kind: append
  destination_type: postgres_operational