sources:
  datalake.orders:
    type: s3
    bucket_name: raw-data
    file_name: order_payments
    file_extension: parquet
    columns:
      payment_type: payment_type
destination:
  table: payment_type
  schema: public
  primary_key: payment_type_id
  business_keys:
    - payment_type_code
  kind: append
  destination_type: postgres_operational