sources:
  operational.status:
    type: postgres_operational
    table: order_status_type
    schema: public
    columns:
      order_status_type_id: order_status_type_id
      order_status_type_code: order_status_type_code
      order_status_type_description: order_status_type_description

destination:
  table: dim_order_status_type
  schema: dw
  primary_key: order_status_type_id
  business_keys:
    - order_status_type_code
  kind: append
  destination_type: postgres_datawarehouse