sources:
  datalake.geolocation:
    type: s3
    bucket_name: sources
    file_name: geolocation_dataset
    file_extension: csv
destination:
  destination_type: s3
  bucket_name: raw-data
  file_name: ref-geolocation.parquet